services:
    postgres:
        image: postgres
        container_name: nest-clean-pg
        restart: always
        ports:
            - 15432:5432
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: nest-clean
        volumes:
            - pgdata:/var/lib/postgresql/data/

    cache:
        image: redis
        container_name: nest-clean-cache
        ports:
            - 6379:6379
        volumes:
            - redis:/data

volumes:
    pgdata:
    redis:
